version: "3.7"

services:
  mysql:
    image: mysql:5.7.29
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
